/**
 * Auto-generated route tree
 * This file is generated by @tanstack/router-plugin
 * DO NOT EDIT MANUALLY
 */

// Placeholder for TanStack Router codegen
// Run `pnpm dev` to generate actual route tree
export const routeTree = {};
